pipeline {
  agent any
  tools {
    jdk   'JDK_21'        // must match the NAME in your screenshot
    maven 'Maven_3.9.9'   // name must match exactly (version 3.9.11 is fine)
  }
  options { skipStagesAfterUnstable() }
  stages {
    stage('Env sanity') {
      steps {
        sh '''
          echo "JAVA_HOME=$JAVA_HOME"
          echo "MAVEN_HOME=$MAVEN_HOME"
          which java && java -version
          which mvn  && mvn -version
        '''
      }
    }
    stage('Build')  { steps { sh 'mvn -B -DskipTests clean package' } }
    stage('Test')   { steps { sh 'mvn test' ; junit 'target/surefire-reports/*.xml' } }
    stage('Deliver'){ steps { sh './jenkins/scripts/deliver.sh' } }
  }
}
